version: '3.4'
services:
  http-backend:
    image: mendhak/http-https-echo
    ports:
      - 8081:80
  varnish:
    build:
      context: varnish/. 
      args:
        BACKEND_HOST: http-backend
        BACKEND_PORT: 80
        VARNISH_MAJOR_VERSION: 60
    image: varnish
    ports:
      - 8080:80
    volumes:
        - ./varnish/user_configs:/etc/varnish/user_configs
